name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]

    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/heads/docs') != true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.11

      - name: Setup pytest
        run: |
          pip install pytest pytest-github-actions-annotate-failures 

      - name: Setup GCC annotations
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Setup MSVC annotations
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Install
        run: |
          pip install -q .

      - name: Run tests
        run: |
          pytest

  # docs:
  #   name: Documentation
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'

  #     - name: Setup CMake
  #       uses: jwlawson/actions-setup-cmake@v1.11

  #     - name: Install requirements
  #       run: |
  #         pip install --user -r docs/requirements.txt
  #         sudo apt install pandoc

  #     - name: Configure
  #       shell: bash
  #       run: |
  #         cmake -S . -B build -DPython_EXECUTABLE="$(which python)"

  #     - name: Build
  #       run: |
  #         cmake --build build -j 2

  #     - name: Build documentation
  #       run: |
  #         cmake --build build --target docs

  #     - name: Check links
  #       run: |
  #         cmake --build build --target docs_linkcheck
